# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
        environment:
          ANSIBLE_HOST_KEY_CHECKING: False
      
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: libdb
          POSTGRES_PASSWORD: libdb


        working_directory: ~/repo
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            pip install --upgrade setuptools
            sudo apt-get install python3-venv
            python3 -m venv myenv
            . myenv/bin/activate
            pip install tox
            
      Step 3: run linter and tests (will all be run by tox command)
      - run:
          name: run tests
          command: |          
            # Run tox
            . myenv/bin/activate
            # Whenever we change the project dependencies we have to tell tox to recreate our environments 
            tox --recreate # Force tox to recreate the venv

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = kevinlm" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc      


      - run:
          name: create packages
          command: |
            python3 setup.py sdist bdist_wheel

      - run:
          name: upload to pypi
          command: |
            . myenv/bin/activate
            pip install twine
            twine upload --skip-existing ./dist/*
      

      - add_ssh_keys:
          fingerprints:
              - "86:65:f4:ef:e4:80:cf:20:ea:12:42:ad:6f:ed:78:52"
     
      - run:
          name: executing ansible to a remote server
          command: |
            . myenv/bin/activate
            pip install ansible
            #ansible web-server -m ping -i ansible/hosts.ini
            ansible-playbook -i ansible/hosts.ini ansible/playbook.yml
            
            